# Generated by Django 5.0.1 on 2024-01-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="email",
        ),
        migrations.RemoveField(
            model_name="record",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="record",
            name="last_name",
        ),
        migrations.AddField(
            model_name="record",
            name="intro",
            field=models.CharField(default="Default Intro Text", max_length=255),
        ),
    ]
