# Generated by Django 5.0.1 on 2024-01-25 04:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_remove_record_email_remove_record_first_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="record",
            old_name="address",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="record",
            name="phone",
        ),
    ]
