# Generated by Django 5.0.1 on 2024-01-25 04:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_record_end_datetime_record_start_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="end_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="record",
            name="start_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
