# Generated by Django 5.0.1 on 2024-01-25 04:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_alter_record_end_datetime_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="state",
        ),
        migrations.RemoveField(
            model_name="record",
            name="zipcode",
        ),
    ]
